spring:
  datasource:
    url: jdbc:mysql://bj-cdb-7ipkvc5q.sql.tencentcdb.com:63670/bda?characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: Dsp750403
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 43.138.50.35
    port: 5672
    username: bda
    password: dsp750403
    virtual-host: /
    # 消费者配置手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
    # 确认消息发送到交换机上
    publisher-confirms: true
    # 确认消息已发送到队列
    publisher-returns: true

  redis:
    host: bj-crs-j4wwda9g.sql.tencentcdb.com
    port: 21722
    password: Dsp750403

ftp:
  ip: 43.138.50.35
  port: 21
  userName: bdauser1
  passWord: dsp750403
