server:
  port: 8888

spring:
  application:
    name: BDA-Java
  mail:
    default-encoding: UTF-8
    host: smtp.163.com #SMTP服务器地址
    username: BDA_DSP
    password: UYXEIOVFIUYHAAMX
    properties:
      from: BDA_DSP@163.com

  datasource:
    url: jdbc:mysql://localhost:3306/bda?characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 消费者配置手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
    # 确认消息发送到交换机上
    publisher-confirms: true
    # 确认消息已发送到队列
    publisher-returns: true

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

restTemplate:
  parameter:
    connect-timeout: 6000
    read-timeout: 6000

ftp:
  ip: 192.168.18.2
  port: 21
  userName: bdauser
  passWord: bdauser
