spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bda?characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://bj-cdb-7ipkvc5q.sql.tencentcdb.com:63670/bda?characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
#    username: root
#    password: Dsp750403
#    driver-class-name: com.mysql.jdbc.Driver
#
#  redis:
#    host: bj-crs-j4wwda9g.sql.tencentcdb.com
#    port: 21722
#    password: Dsp750403

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 消费者配置手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
    # 确认消息发送到交换机上
    publisher-confirms: true
    # 确认消息已发送到队列
    publisher-returns: true

#ftp:
#  ip: localhost
#  port: 21
#  userName: bdauser
#  passWord: bdauser

ftp:
  ip: 192.168.1.106
  port: 7777
  userName: admin
  passWord: admin
